### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by yuta1024** [yuta1024/isucon9#17]
# Todo List
## 事前準備
- [x] 再起動試験

## コンテスト開始すぐ
- [x] 全インスタンスに `init` を実行
- [x] ソースコードなどを git 管理下へ
- [x] Docker で動作するように対応
  - [x] `fastcgi_param` で PHP 環境へ DB ホストを渡す(e.g. [docker](https://github.com/yuta1024/isucon9/blob/master/src/docker/conf/nginx.conf#L47))
  - [x] `getenv` で `fastcgi_param` で渡された値を取得する(e.g. [isucon8](https://github.com/isucon/isucon8-qualify/blob/master/webapp/php/app.php#L60))
- [ ] fabric の対応
  - [ ] [hosts.py](https://github.com/yuta1024/isucon9/blob/master/infra/fabfile/hosts.py) の修正
  - [ ] [deploy.py](https://github.com/yuta1024/isucon9/blob/master/infra/fabfile/deploy.py) の修正
- [x] デフォルト構成への [kataribe ログ形式](https://github.com/yuta1024/isucon9/blob/master/src/docker/conf/nginx.conf#L19-L20)対応
- [ ] config を除いたデプロイの実施
  - [ ] ベンチ実行
- [ ] ミドルウェア入れ替え
- [ ] 再起動試験

## コンテスト終了後
- [x] Discord の通知用 Webhook を revoke
